# Generated by Django 6.0.3 on 2026-09-16 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('room_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite')], max_length=20)),
                ('price_per_night', models.FloatField(validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(100000)])),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_available', models.BooleanField(default=True)),
                ('check_in_date', models.DateField(auto_now_add=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('country', models.CharField(default='India', max_length=50)),
            ],
            options={
                'verbose_name': 'Hotel Booking',
                'verbose_name_plural': 'Hotel Bookings',
                'db_table': 'hotel_booking',
                'ordering': ['guest_name'],
            },
        ),
    ]
